name: Sync to Hugging Face hu

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
        with:
          fetch-depth: 0
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://zrentala:$HF_TOKEN@huggingface.co/spaces/zrentala/ConnectivityVisualizer main
